# Generated by Django 5.1.2 on 2024-10-10 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('DONO', 'Dono do Mercado'), ('FUNCIONARIO', 'Funcionário do Mercado'), ('CLIENTE', 'Cliente do Mercado')], default='CLIENTE', max_length=20)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('nome', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('tipo', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estoque', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
