# Generated by Django 5.1.2 on 2024-10-10 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='valor',
            new_name='preco',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(14)]),
        ),
    ]
