# Generated by Django 5.1.2 on 2024-10-11 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_remove_produto_id_alter_produto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
