# Generated by Django 5.1.2 on 2024-10-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_alter_produto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
